// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Robot.proto

package Greenfield;

public final class RobotOuterClass {
  private RobotOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RobotOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Greenfield.Robot)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>required int32 port = 2;</code>
     * @return Whether the port field is set.
     */
    boolean hasPort();
    /**
     * <code>required int32 port = 2;</code>
     * @return The port.
     */
    int getPort();

    /**
     * <code>required string ip = 3;</code>
     * @return Whether the ip field is set.
     */
    boolean hasIp();
    /**
     * <code>required string ip = 3;</code>
     * @return The ip.
     */
    java.lang.String getIp();
    /**
     * <code>required string ip = 3;</code>
     * @return The bytes for ip.
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>optional bool hello = 4;</code>
     * @return Whether the hello field is set.
     */
    boolean hasHello();
    /**
     * <code>optional bool hello = 4;</code>
     * @return The hello.
     */
    boolean getHello();

    /**
     * <code>optional bool mechanic = 5;</code>
     * @return Whether the mechanic field is set.
     */
    boolean hasMechanic();
    /**
     * <code>optional bool mechanic = 5;</code>
     * @return The mechanic.
     */
    boolean getMechanic();

    /**
     * <code>optional bool goodbye = 6;</code>
     * @return Whether the goodbye field is set.
     */
    boolean hasGoodbye();
    /**
     * <code>optional bool goodbye = 6;</code>
     * @return The goodbye.
     */
    boolean getGoodbye();
  }
  /**
   * Protobuf type {@code Greenfield.Robot}
   */
  public  static final class Robot extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Greenfield.Robot)
      RobotOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Robot.newBuilder() to construct.
    private Robot(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Robot() {
      ip_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Robot();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Robot(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              port_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              ip_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              hello_ = input.readBool();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              mechanic_ = input.readBool();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              goodbye_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Greenfield.RobotOuterClass.internal_static_Greenfield_Robot_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Greenfield.RobotOuterClass.internal_static_Greenfield_Robot_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Greenfield.RobotOuterClass.Robot.class, Greenfield.RobotOuterClass.Robot.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     * @return Whether the id field is set.
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 id = 1;</code>
     * @return The id.
     */
    public int getId() {
      return id_;
    }

    public static final int PORT_FIELD_NUMBER = 2;
    private int port_;
    /**
     * <code>required int32 port = 2;</code>
     * @return Whether the port field is set.
     */
    public boolean hasPort() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 port = 2;</code>
     * @return The port.
     */
    public int getPort() {
      return port_;
    }

    public static final int IP_FIELD_NUMBER = 3;
    private volatile java.lang.Object ip_;
    /**
     * <code>required string ip = 3;</code>
     * @return Whether the ip field is set.
     */
    public boolean hasIp() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required string ip = 3;</code>
     * @return The ip.
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ip_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ip = 3;</code>
     * @return The bytes for ip.
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HELLO_FIELD_NUMBER = 4;
    private boolean hello_;
    /**
     * <code>optional bool hello = 4;</code>
     * @return Whether the hello field is set.
     */
    public boolean hasHello() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional bool hello = 4;</code>
     * @return The hello.
     */
    public boolean getHello() {
      return hello_;
    }

    public static final int MECHANIC_FIELD_NUMBER = 5;
    private boolean mechanic_;
    /**
     * <code>optional bool mechanic = 5;</code>
     * @return Whether the mechanic field is set.
     */
    public boolean hasMechanic() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional bool mechanic = 5;</code>
     * @return The mechanic.
     */
    public boolean getMechanic() {
      return mechanic_;
    }

    public static final int GOODBYE_FIELD_NUMBER = 6;
    private boolean goodbye_;
    /**
     * <code>optional bool goodbye = 6;</code>
     * @return Whether the goodbye field is set.
     */
    public boolean hasGoodbye() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional bool goodbye = 6;</code>
     * @return The goodbye.
     */
    public boolean getGoodbye() {
      return goodbye_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, port_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ip_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeBool(4, hello_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeBool(5, mechanic_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeBool(6, goodbye_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, port_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ip_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, hello_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, mechanic_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, goodbye_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Greenfield.RobotOuterClass.Robot)) {
        return super.equals(obj);
      }
      Greenfield.RobotOuterClass.Robot other = (Greenfield.RobotOuterClass.Robot) obj;

      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (getId()
            != other.getId()) return false;
      }
      if (hasPort() != other.hasPort()) return false;
      if (hasPort()) {
        if (getPort()
            != other.getPort()) return false;
      }
      if (hasIp() != other.hasIp()) return false;
      if (hasIp()) {
        if (!getIp()
            .equals(other.getIp())) return false;
      }
      if (hasHello() != other.hasHello()) return false;
      if (hasHello()) {
        if (getHello()
            != other.getHello()) return false;
      }
      if (hasMechanic() != other.hasMechanic()) return false;
      if (hasMechanic()) {
        if (getMechanic()
            != other.getMechanic()) return false;
      }
      if (hasGoodbye() != other.hasGoodbye()) return false;
      if (hasGoodbye()) {
        if (getGoodbye()
            != other.getGoodbye()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasPort()) {
        hash = (37 * hash) + PORT_FIELD_NUMBER;
        hash = (53 * hash) + getPort();
      }
      if (hasIp()) {
        hash = (37 * hash) + IP_FIELD_NUMBER;
        hash = (53 * hash) + getIp().hashCode();
      }
      if (hasHello()) {
        hash = (37 * hash) + HELLO_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getHello());
      }
      if (hasMechanic()) {
        hash = (37 * hash) + MECHANIC_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getMechanic());
      }
      if (hasGoodbye()) {
        hash = (37 * hash) + GOODBYE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getGoodbye());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Greenfield.RobotOuterClass.Robot parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Greenfield.RobotOuterClass.Robot parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Greenfield.RobotOuterClass.Robot parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Greenfield.RobotOuterClass.Robot parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Greenfield.RobotOuterClass.Robot parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Greenfield.RobotOuterClass.Robot parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Greenfield.RobotOuterClass.Robot parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Greenfield.RobotOuterClass.Robot parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Greenfield.RobotOuterClass.Robot parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Greenfield.RobotOuterClass.Robot parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Greenfield.RobotOuterClass.Robot parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Greenfield.RobotOuterClass.Robot parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Greenfield.RobotOuterClass.Robot prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Greenfield.Robot}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Greenfield.Robot)
        Greenfield.RobotOuterClass.RobotOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Greenfield.RobotOuterClass.internal_static_Greenfield_Robot_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Greenfield.RobotOuterClass.internal_static_Greenfield_Robot_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Greenfield.RobotOuterClass.Robot.class, Greenfield.RobotOuterClass.Robot.Builder.class);
      }

      // Construct using Greenfield.RobotOuterClass.Robot.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        ip_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        hello_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        mechanic_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        goodbye_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Greenfield.RobotOuterClass.internal_static_Greenfield_Robot_descriptor;
      }

      @java.lang.Override
      public Greenfield.RobotOuterClass.Robot getDefaultInstanceForType() {
        return Greenfield.RobotOuterClass.Robot.getDefaultInstance();
      }

      @java.lang.Override
      public Greenfield.RobotOuterClass.Robot build() {
        Greenfield.RobotOuterClass.Robot result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Greenfield.RobotOuterClass.Robot buildPartial() {
        Greenfield.RobotOuterClass.Robot result = new Greenfield.RobotOuterClass.Robot(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.port_ = port_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.ip_ = ip_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.hello_ = hello_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.mechanic_ = mechanic_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.goodbye_ = goodbye_;
          to_bitField0_ |= 0x00000020;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Greenfield.RobotOuterClass.Robot) {
          return mergeFrom((Greenfield.RobotOuterClass.Robot)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Greenfield.RobotOuterClass.Robot other) {
        if (other == Greenfield.RobotOuterClass.Robot.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        if (other.hasIp()) {
          bitField0_ |= 0x00000004;
          ip_ = other.ip_;
          onChanged();
        }
        if (other.hasHello()) {
          setHello(other.getHello());
        }
        if (other.hasMechanic()) {
          setMechanic(other.getMechanic());
        }
        if (other.hasGoodbye()) {
          setGoodbye(other.getGoodbye());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasPort()) {
          return false;
        }
        if (!hasIp()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Greenfield.RobotOuterClass.Robot parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Greenfield.RobotOuterClass.Robot) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       * @return Whether the id field is set.
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 id = 1;</code>
       * @return The id.
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>required int32 port = 2;</code>
       * @return Whether the port field is set.
       */
      public boolean hasPort() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int32 port = 2;</code>
       * @return The port.
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>required int32 port = 2;</code>
       * @param value The port to set.
       * @return This builder for chaining.
       */
      public Builder setPort(int value) {
        bitField0_ |= 0x00000002;
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 port = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000002);
        port_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object ip_ = "";
      /**
       * <code>required string ip = 3;</code>
       * @return Whether the ip field is set.
       */
      public boolean hasIp() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required string ip = 3;</code>
       * @return The ip.
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ip_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ip = 3;</code>
       * @return The bytes for ip.
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ip = 3;</code>
       * @param value The ip to set.
       * @return This builder for chaining.
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ip = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>required string ip = 3;</code>
       * @param value The bytes for ip to set.
       * @return This builder for chaining.
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        ip_ = value;
        onChanged();
        return this;
      }

      private boolean hello_ ;
      /**
       * <code>optional bool hello = 4;</code>
       * @return Whether the hello field is set.
       */
      public boolean hasHello() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional bool hello = 4;</code>
       * @return The hello.
       */
      public boolean getHello() {
        return hello_;
      }
      /**
       * <code>optional bool hello = 4;</code>
       * @param value The hello to set.
       * @return This builder for chaining.
       */
      public Builder setHello(boolean value) {
        bitField0_ |= 0x00000008;
        hello_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool hello = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearHello() {
        bitField0_ = (bitField0_ & ~0x00000008);
        hello_ = false;
        onChanged();
        return this;
      }

      private boolean mechanic_ ;
      /**
       * <code>optional bool mechanic = 5;</code>
       * @return Whether the mechanic field is set.
       */
      public boolean hasMechanic() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional bool mechanic = 5;</code>
       * @return The mechanic.
       */
      public boolean getMechanic() {
        return mechanic_;
      }
      /**
       * <code>optional bool mechanic = 5;</code>
       * @param value The mechanic to set.
       * @return This builder for chaining.
       */
      public Builder setMechanic(boolean value) {
        bitField0_ |= 0x00000010;
        mechanic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool mechanic = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearMechanic() {
        bitField0_ = (bitField0_ & ~0x00000010);
        mechanic_ = false;
        onChanged();
        return this;
      }

      private boolean goodbye_ ;
      /**
       * <code>optional bool goodbye = 6;</code>
       * @return Whether the goodbye field is set.
       */
      public boolean hasGoodbye() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional bool goodbye = 6;</code>
       * @return The goodbye.
       */
      public boolean getGoodbye() {
        return goodbye_;
      }
      /**
       * <code>optional bool goodbye = 6;</code>
       * @param value The goodbye to set.
       * @return This builder for chaining.
       */
      public Builder setGoodbye(boolean value) {
        bitField0_ |= 0x00000020;
        goodbye_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool goodbye = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearGoodbye() {
        bitField0_ = (bitField0_ & ~0x00000020);
        goodbye_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Greenfield.Robot)
    }

    // @@protoc_insertion_point(class_scope:Greenfield.Robot)
    private static final Greenfield.RobotOuterClass.Robot DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Greenfield.RobotOuterClass.Robot();
    }

    public static Greenfield.RobotOuterClass.Robot getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Robot>
        PARSER = new com.google.protobuf.AbstractParser<Robot>() {
      @java.lang.Override
      public Robot parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Robot(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Robot> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Robot> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Greenfield.RobotOuterClass.Robot getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Greenfield_Robot_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Greenfield_Robot_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Robot.proto\022\nGreenfield\"_\n\005Robot\022\n\n\002id" +
      "\030\001 \002(\005\022\014\n\004port\030\002 \002(\005\022\n\n\002ip\030\003 \002(\t\022\r\n\005hell" +
      "o\030\004 \001(\010\022\020\n\010mechanic\030\005 \001(\010\022\017\n\007goodbye\030\006 \001" +
      "(\010"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Greenfield_Robot_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Greenfield_Robot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Greenfield_Robot_descriptor,
        new java.lang.String[] { "Id", "Port", "Ip", "Hello", "Mechanic", "Goodbye", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
